--- #YAML:1.0
name:               Module-Starter-Plugin-Attanium
version:            0.004
abstract:           Obsolete: use CGI::Application::Structured::Tools
author:
    - Gordon Van Amburg
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBIx::Class::Schema::Loader:  0
    ExtUtils::Command:    0
    File::Basename:       0
    File::Slurp:          0
    File::Spec:           0
    FindBin:              0
    HTML::Template:       0
    Module::Signature:    0
    Module::Starter:      0
    Module::Starter::Plugin::Template:  1.5
    Module::Starter::Simple:  1.5
    Pod::Coverage:        0.18
    Pod::Usage:           0
    Test::More:           0
    Test::Pod:            1.22
    Test::Pod::Coverage:  1.08
    Test::WWW::Mechanize::CGIApp:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
